name: Build & Test

on:
  pull_request:
    branches:    
      - '*'
  push:
    branches:
      - '*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install
        run: cd projects && ./install.sh

      - name: Run Tests
        run: cd examples && ./test.sh


